In [1]:
import numpy as np
import pandas as pd
import time

In [2]:
np.__version__

'2.3.1'

In [3]:
a0=np.array([1])
print("0D->",a0)                  #creates a 0D array
a1=np.array([1,2,3,4])
print("1D ->",a1)                 #creates a 1D array
a2=np.array([[1,2,3,4],[5,6,7,8]])
print("2D ->",a2)                 #creates a 2D array
a3=np.array([[[1,2,3,4],[5,6,7,8],[9,0,1,2]]])
print("3D ->",a3)                 #creates a 3D array

0D-> [1]
1D -> [1 2 3 4]
2D -> [[1 2 3 4]
 [5 6 7 8]]
3D -> [[[1 2 3 4]
  [5 6 7 8]
  [9 0 1 2]]]


In [4]:
a3.ndim

3

In [5]:
a4=np.array([[[1,2,3,4],[5,6,7,8]],[[9,0,1,2],[3,4,5,6]]])          #another way to create a 3d array
print(a4,a4.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[9 0 1 2]
  [3 4 5 6]]] 3


In [6]:
a4.shape

(2, 2, 4)

In [7]:
pa1=pd.DataFrame(a2)        #converting an 2d array into df
pa1

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [8]:
z1=np.zeros((2,3))      #creates a zero matrix  
z1      #return type of individual values is float

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
o1=np.ones((2,3))       #creates a one matrix
o1                      #return type of individual values is float

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ar1=np.arange(1,20,2,'float')       #creates 1D array of elements in the given range 
# arg1-> lower limit , arg2-> upper limit
# arg3-> step , arg4-> datatype of return values
ar1

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [11]:
o1.astype('int')        #with this we can change the datatype of these arrays

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
ar1=np.random.randint(10,size=(4,5))    #random array of int
ar1

array([[7, 6, 2, 3, 0],
       [3, 2, 1, 9, 9],
       [0, 3, 3, 2, 4],
       [0, 9, 0, 2, 7]], dtype=int32)

In [13]:
ar2=np.random.random((2,4,5))     #create a random array of values b/w [0,1]
ar2

array([[[0.11155142, 0.30336478, 0.07924667, 0.72444833, 0.58985914],
        [0.9532648 , 0.44078963, 0.70101783, 0.27660679, 0.41657521],
        [0.13761345, 0.13370019, 0.10732094, 0.32387325, 0.23238369],
        [0.42644327, 0.47125256, 0.2698113 , 0.29212755, 0.29486469]],

       [[0.84517085, 0.51758322, 0.42873228, 0.00563863, 0.96619494],
        [0.64974466, 0.21532483, 0.47139781, 0.69694134, 0.88327739],
        [0.27086694, 0.32791744, 0.67667768, 0.59932751, 0.82355032],
        [0.76139018, 0.87476572, 0.05454062, 0.09910366, 0.45197582]]])

In [14]:
ar3=np.random.rand(4,5)         #creates a random array of values 0-1
ar3

array([[0.73667446, 0.76027558, 0.77028558, 0.47596818, 0.25279699],
       [0.69500826, 0.21872042, 0.71314684, 0.62321937, 0.3120063 ],
       [0.41210261, 0.95605408, 0.35359303, 0.69818142, 0.74086902],
       [0.93729483, 0.45556953, 0.31725096, 0.85379621, 0.37633558]])

In [15]:
np.random.randn(5)      #creates an array of normal distrbution

array([ 0.77119782,  1.43470994, -1.98586118, -0.82653224,  1.44033439])

seed()

In [16]:
np.random.seed(0)
sa0=np.random.randint(100,size=(2,3))
sa0     

array([[44, 47, 64],
       [67, 67,  9]], dtype=int32)

In [17]:
np.random.seed(2)
spa1=pd.DataFrame(np.random.randint(1000,size=(3,3)))
spa1

0    1    2
0  168  527  493
1  584  534  299
2  466   75  360

Accessing values in np.array

In [18]:
a1[2]       #for 1D
#returns the datatype and the value at that index

np.int64(3)

In [19]:
a2[1,1]     #for a single value in 2D
a2[1]       #for whole row 

array([5, 6, 7, 8])

In [20]:
print(a4[1,1,1] )      #for single value in 3D
print(a4[1,1])         #for single row in 3D
print(a4[1])           #for a 2D matrix 

4
[3 4 5 6]
[[9 0 1 2]
 [3 4 5 6]]


Slicing

In [21]:
a1[1:]      #1D

array([2, 3, 4])

In [22]:
a2[1:,2:]   #2d
a2[1:]

array([[5, 6, 7, 8]])

In [23]:
a4[1:]      #3d
a4[1:,0:]
a4[1:,0:,1:]

array([[[0, 1, 2],
        [4, 5, 6]]])

In [24]:
arr1=np.random.randint(-100,100,size=(10,))
print(arr1)

ind=np.array([2,3,4])

print(arr1[ind])        #we can access indices of array with the values of another array

co=arr1>0
print(arr1[co])     #we can filter values based on some condition

[-93  62  77  -5 -25 -53 -37 -69  48  24]
[ 77  -5 -25]
[62 77 48 24]


In [25]:
np.random.uniform(low=5,high=10,size=(4,5))

array([[9.09113361, 8.41512997, 7.49280585, 7.93398489, 8.59877116],
       [6.29249043, 7.7310366 , 7.03653916, 5.88492312, 9.84816203],
       [6.48509179, 6.43934408, 5.58096659, 5.90863519, 7.47144884],
       [7.82882565, 6.10917584, 8.83745585, 7.88654034, 5.83911655]])

For the same data which is faster np or pd

In [26]:
for i in range(10):

    t1=time.time()
    np.mean(a2)
    t2=time.time()
    np_time= t2-t1

    t1=time.time()
    pa1.mean()
    t2=time.time()
    pd_time=t2-t1

    print("numpy: ",np_time,"Pandas: ",pd_time)

numpy:  0.0 Pandas:  0.0011057853698730469
numpy:  0.0 Pandas:  0.0
numpy:  0.0 Pandas:  0.0
numpy:  0.0 Pandas:  0.004084587097167969
numpy:  0.0002887248992919922 Pandas:  0.0
numpy:  0.0 Pandas:  0.0011126995086669922
numpy:  0.0 Pandas:  0.00035834312438964844
numpy:  0.0 Pandas:  0.0010738372802734375
numpy:  0.0 Pandas:  0.0005104541778564453
numpy:  0.0 Pandas:  0.0


Arithmatic Operations

In [27]:
print(a0)
print()
print(a1)
print()
print(a2)
print()
print(a3)
print()
print(a4)

[1]

[1 2 3 4]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2 3 4]
  [5 6 7 8]
  [9 0 1 2]]]

[[[1 2 3 4]
  [5 6 7 8]]

 [[9 0 1 2]
  [3 4 5 6]]]


In [28]:
ao1=np.random.randint(10,size=(5,))
ao2=np.random.randint(100,size=(5,))

In [29]:
a4.size

16

In [30]:
a4.shape

(2, 2, 4)

In [31]:
a4.ndim

3

In [32]:
ao1+ao2     #for addition shape has to be same

array([25, 24, 82, 65, 97], dtype=int32)

In [33]:
ao2-ao1     #for susbstraction shape has to be same

array([ 9, 20, 64, 49, 83], dtype=int32)

In [34]:
a4*a2       #for multiplication to happen
#operand1[m*n] and operand2[y*z], then n==y


array([[[ 1,  4,  9, 16],
        [25, 36, 49, 64]],

       [[ 9,  0,  3,  8],
        [15, 24, 35, 48]]])

In [35]:
a4/a2      #for division to happen
#operand1[m*n] and operand2[y*z], then n==y

array([[[1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        ]],

       [[9.        , 0.        , 0.33333333, 0.5       ],
        [0.6       , 0.66666667, 0.71428571, 0.75      ]]])

### Broadcasting

- What is broadcasting?
    - Broadcasting is a feature of NumPy which performs an operation across multiple dimensions of data without replicating the data. This saves time and space. For example, if you have a 3x3 array (A) and want to add a 1x3 array (B), NumPy will add the row of (B) to every row of (A).
    
**The broadcasting rule:**
In order to broadcast, the size of the trailing axes for both arrays in an operation must be either the same size or one of them must be one.

- Rules of Broadcasting
    1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
    
    Example:
    Array A: shape (3, 4)

    Array B: shape (4,)  -> becomes (1, 4) for broadcasting comparison
    

2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.


    Example of compatible dimensions:
     Array A: shape (5, 6)

     Array B: shape (1, 6)  -> compatible (6 == 6, and 1 can be stretched to 5)

     Example of incompatible dimensions:
     Array A: shape (5, 6)
     
     Array B: shape (2, 6)  -> incompatible (5 != 2 and neither is 1)

3. If in any dimension the sizes disagree and neither is equal to 1, an Valueerror is raised.


In [36]:
a4//a2      #floor division

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[9, 0, 0, 0],
        [0, 0, 0, 0]]])

In [37]:
ab=np.random.randint(10,size=(4,4))
ab1=np.random.randint(10,size=(4,4))
ab,ab1

(array([[3, 0, 0, 2],
        [8, 8, 2, 9],
        [6, 5, 6, 6],
        [6, 3, 8, 2]], dtype=int32),
 array([[1, 4, 8, 1],
        [6, 9, 5, 1],
        [2, 4, 7, 6],
        [4, 5, 8, 3]], dtype=int32))

In [38]:
ab+ab1

array([[ 4,  4,  8,  3],
       [14, 17,  7, 10],
       [ 8,  9, 13, 12],
       [10,  8, 16,  5]], dtype=int32)

In [39]:
a4**a2  #power

array([[[       1,        4,       27,      256],
        [    3125,    46656,   823543, 16777216]],

       [[       9,        0,        1,       16],
        [     243,     4096,    78125,  1679616]]])

In [40]:
a4**2

array([[[ 1,  4,  9, 16],
        [25, 36, 49, 64]],

       [[81,  0,  1,  4],
        [ 9, 16, 25, 36]]])

In [41]:
np.square(a1)   #square 

array([ 1,  4,  9, 16])

In [42]:
np.sqrt(a2)     #sqrt

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [43]:
a3%5

array([[[1, 2, 3, 4],
        [0, 1, 2, 3],
        [4, 0, 1, 2]]])

In [44]:
np.sum(a4)

np.int64(66)

In [45]:
np.max(arr1)

np.int32(77)

In [46]:
np.min(arr1)

np.int32(-93)

In [47]:
np.std(a4)      #standard deviation

np.float64(2.54644359843292)

In [48]:
np.var(a4)      #variance

np.float64(6.484375)

In [49]:
np.mean(a4)

np.float64(4.125)

In [50]:
np.median(a4)

np.float64(4.0)

reshape() -> reshapes the array into desired dimensions if the convertion is possible 

In [51]:
ra4=a4.reshape(4,2,2)

In [52]:
ra4.shape

(4, 2, 2)

In [53]:
ra3=a3.reshape(2,2,3)
ra3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [54]:
ra2=np.random.randint(10,size=(1,2,2))

In [55]:
ra2,a2

(array([[[0, 0],
         [5, 7]]], dtype=int32),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [56]:
ra4*ra2     #when working with 3d you have to keep in mind all the three dimensions

array([[[ 0,  0],
        [15, 28]],

       [[ 0,  0],
        [35, 56]],

       [[ 0,  0],
        [ 5, 14]],

       [[ 0,  0],
        [25, 42]]])

In [57]:
a4.shape,ra4.shape,a2.shape,ra2.shape

((2, 2, 4), (4, 2, 2), (2, 4), (1, 2, 2))

In [58]:
a2*a4,(a2*a4).shape

(array([[[ 1,  4,  9, 16],
         [25, 36, 49, 64]],
 
        [[ 9,  0,  3,  8],
         [15, 24, 35, 48]]]),
 (2, 2, 4))

In [59]:
a2+a1       #broadcasting is increasing the size of a1 to be compatible with a2

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [60]:
a1+a4

array([[[ 2,  4,  6,  8],
        [ 6,  8, 10, 12]],

       [[10,  2,  4,  6],
        [ 4,  6,  8, 10]]])

In [61]:
a4

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 0, 1, 2],
        [3, 4, 5, 6]]])

Transpose()

In [62]:
a4.transpose()      #another way to do transpose

array([[[1, 9],
        [5, 3]],

       [[2, 0],
        [6, 4]],

       [[3, 1],
        [7, 5]],

       [[4, 2],
        [8, 6]]])

In [63]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
a5=np.array([[9,8],[7,6],[5,4]])
a5

array([[9, 8],
       [7, 6],
       [5, 4]])

In [65]:
a2[:,:3],a5,np.dot(a2[:,:3],a5)         #dot product

(array([[1, 2, 3],
        [5, 6, 7]]),
 array([[9, 8],
        [7, 6],
        [5, 4]]),
 array([[ 38,  32],
        [122, 104]]))

In [66]:
a2[:,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [67]:
a5

array([[9, 8],
       [7, 6],
       [5, 4]])

In [68]:
# np.dot(a2,ra2)      #will only work if dimensions are same

In [69]:
a2[:,:3] @ a5       #another way of cross product

array([[ 38,  32],
       [122, 104]])

In [70]:
a4.argmax()         #returns the index of largest element

np.int64(8)

In [71]:
a4.argmin()         #returns the index of smallest element

np.int64(9)

In [72]:
np.absolute(arr1)           #returns the absolute value     


array([93, 62, 77,  5, 25, 53, 37, 69, 48, 24], dtype=int32)

In [73]:
np.eye(4,5,1,'int')       #creates a 2D identity matrix
#arg1,arg2 -> rows and columns
#arg3 -> offset
#ar4 -> datatype

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [74]:
np.sin(a2)          #sin valu

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825]])

In [75]:
a1

array([1, 2, 3, 4])

In [76]:
np.diagflat(a1)     #flats the matrix into an diagonal matrix with diagonal values being the values of the array

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [77]:
d=np.diag_indices(4,2)      #returns the indices to access the main diagonal
#arg1 -> size of matrix
#arg2 -> ndim
a=np.arange(16).reshape(4,4)
a[d]=1111
a

array([[1111,    1,    2,    3],
       [   4, 1111,    6,    7],
       [   8,    9, 1111,   11],
       [  12,   13,   14, 1111]])

In [78]:
np.apply_along_axis(sorted,1,a)

array([[   1,    2,    3, 1111],
       [   4,    6,    7, 1111],
       [   8,    9,   11, 1111],
       [  12,   13,   14, 1111]])

In [79]:
np.apply_along_axis(sorted,0,a)

array([[   4,    1,    2,    3],
       [   8,    9,    6,    7],
       [  12,   13,   14,   11],
       [1111, 1111, 1111, 1111]])

In [80]:
def addi(a):
     return (a[0] + a[-1])

ar11=np.apply_along_axis(np.max,0,a)      
#arg1- > function
# axis -> 0==row 1==column
# arg3 -> array 
ar11 

array([1111, 1111, 1111, 1111])

In [81]:
np.apply_over_axes(np.max,a,0)      #same as above function ,only difference is that the ouput can be varied based on the axis
#arg1- > function
# arg2 -> array 
# arg3 -> axis -> 0==row 1==column  

array([[1111, 1111, 1111, 1111]])

In [82]:
np.nanargmin(a2)        #index of min leaving NaN values 
np.nanargmax(a2)

np.int64(7)

In [83]:
np.amax(a2,1)       #returns the maxvalue along the axis
np.amin(a2,1)

array([1, 5])

In [84]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
a_=np.insert(a2,1,11,axis=1)        #inserts value at the given index
#arg1 -> array               #when working with 2d or higher dimensions axis must be specidfied ,else it will convert the ndim array into a 1d array.      
#arg2 -> index
#arg3 -> value

a_.shape,a_

((2, 5),
 array([[ 1, 11,  2,  3,  4],
        [ 5, 11,  6,  7,  8]]))

In [86]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
np.delete(a_,1,axis=1)     #delets from index
#it also flattens the array if axis not given

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
np.append(a2,a_,axis=1)     #appends the two arrays

array([[ 1,  2,  3,  4,  1, 11,  2,  3,  4],
       [ 5,  6,  7,  8,  5, 11,  6,  7,  8]])

In [89]:
r1=np.random.rand(4,5)
r1,np.around(r1,decimals=1)        #rounds off to the nearest int if decimals not provided
#negative decimals round off to the nearest 10

(array([[0.32287421, 0.76193   , 0.93262856, 0.71121724, 0.51743076],
        [0.8844716 , 0.55363384, 0.5736425 , 0.39393329, 0.92654675],
        [0.00554442, 0.7284985 , 0.35575363, 0.21293324, 0.36202741],
        [0.87830029, 0.36332589, 0.50320692, 0.76748826, 0.91447557]]),
 array([[0.3, 0.8, 0.9, 0.7, 0.5],
        [0.9, 0.6, 0.6, 0.4, 0.9],
        [0. , 0.7, 0.4, 0.2, 0.4],
        [0.9, 0.4, 0.5, 0.8, 0.9]]))

In [90]:
np.flip(a2,axis=1)     #flips the array ,if no axis reverses the element

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

In [91]:
np.fliplr(a2)       # flips in L->R 

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

In [92]:
np.flipud(a2)       #flips U->R

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [93]:
np.triu(a3)     #return the upper part of the trianegle

array([[[1, 2, 3, 4],
        [0, 6, 7, 8],
        [0, 0, 1, 2]]])

In [94]:
np.tril(a3)         #return the left side of matrix

array([[[1, 0, 0, 0],
        [5, 6, 0, 0],
        [9, 0, 1, 0]]])

In [95]:
np.tri(3,3,-1)      #returns a left part of matrix with values of 1 
# arg1,arg2 -> rows and columns
#arg3 -> offset

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [96]:
ea=np.empty((1,2,2), dtype="int")      #creates a random array and no use of seed
ea  #it creates an empty array

array([[[0, 1],
        [2, 3]]])

In [97]:
np.empty_like(ea)           #creates another random array of same size as passed inside the function

array([[[25895968444448860, 23925768161198147],
        [32370111954616435, 22518277314052188]]])

In [98]:
np.zeros_like(ea,subok=True,dtype='float',order='F')       #creates a zero array of same size as passed inside the function
# subok  : If true, then newly created array will be sub-class of array;otherwise, a base-class array
# order  : C_contiguous or F_contiguous
#          C-contiguous order in memory(last index varies the fastest)  C order means that operating row-rise on the array will be slightly quicker
#          FORTRAN-contiguous order in memory (first index varies the fastest).

array([[[0., 0.],
        [0., 0.]]])

In [99]:
a6=np.random.randint(10,size=(3,3))
a6


array([[7, 1, 9],
       [2, 1, 0],
       [7, 1, 8]], dtype=int32)

In [100]:
np.diag(a6)     #prints the diagonal values of the matrix

array([7, 1, 8], dtype=int32)

In [101]:
np.asmatrix(a5)     #returns a matrix 

matrix([[9, 8],
        [7, 6],
        [5, 4]])

In [102]:
a2,a6

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[7, 1, 9],
        [2, 1, 0],
        [7, 1, 8]], dtype=int32))

In [103]:
np.bmat([a2,a6[:2]])        #returns a matrix by concatinating tw nested objetcs

matrix([[1, 2, 3, 4, 7, 1, 9],
        [5, 6, 7, 8, 2, 1, 0]])

In [104]:
l1=[[1,2,3],[8,9]]
l2=[[4,5,6],[6,7]]
np.bmat([l1,l2])        
# np.bmat('l1;l2')        #for this way dimension should be min of 2d

matrix([[1, 2, 3, 8, 9, 4, 5, 6, 6, 7]])

In [105]:
a6

array([[7, 1, 9],
       [2, 1, 0],
       [7, 1, 8]], dtype=int32)

In [106]:
np.roll(a6,2)       #shifts the elemnts of the array by the specified factor   
#by default axis is 1

array([[1, 8, 7],
       [1, 9, 2],
       [1, 0, 7]], dtype=int32)

In [107]:
np.roll(a6,5,axis=0)    #shifts entire row when axis is 0

array([[2, 1, 0],
       [7, 1, 8],
       [7, 1, 9]], dtype=int32)

In [108]:
np.identity(5)      #creates an square identity array 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [109]:
np.place(a6,a6>6,[18])      #makes changes in the original array based on some condition
#arg1 -> input array
#arg2 -> condition
#arg3 -> value to be replaced with
a6

array([[18,  1, 18],
       [ 2,  1,  0],
       [18,  1, 18]], dtype=int32)

In [110]:
np.extract(a6>6,a6)     # returns the values that satisfy the contion
#if arg1 -> condition and
#  arg2 -> array returns values

#if 
# arg1-> array and
#  arg2-> condition 

np.extract(a6,a6>4)     #returns a bool array 

array([ True, False,  True, False, False,  True, False,  True])

In [111]:
np.compress([1,2],a6,axis=1)       #returns a sliced string  
# arg1 -> index
# arg2 -> array

# arg3 -> axis (optional)

array([[18,  1],
       [ 2,  1],
       [18,  1]], dtype=int32)

In [112]:
np.rot90(a3,2,axes=(1,2)),a3       #rotates the arry by 90 degrees anti clock wise
# arg1 -> array
# arg2 -> number of times to be rotated
# arg3 -> axes on which to be rotated

(array([[[2, 1, 0, 9],
         [8, 7, 6, 5],
         [4, 3, 2, 1]]]),
 array([[[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 0, 1, 2]]]))

In [113]:
t1=np.tile(a6,(3,2,2))    #returns the array by repeting its value n time
# arg1 -> array
# arg2 -> times of repetition   ,this be also passed as an nd 
t1

array([[[18,  1, 18, 18,  1, 18],
        [ 2,  1,  0,  2,  1,  0],
        [18,  1, 18, 18,  1, 18],
        [18,  1, 18, 18,  1, 18],
        [ 2,  1,  0,  2,  1,  0],
        [18,  1, 18, 18,  1, 18]],

       [[18,  1, 18, 18,  1, 18],
        [ 2,  1,  0,  2,  1,  0],
        [18,  1, 18, 18,  1, 18],
        [18,  1, 18, 18,  1, 18],
        [ 2,  1,  0,  2,  1,  0],
        [18,  1, 18, 18,  1, 18]],

       [[18,  1, 18, 18,  1, 18],
        [ 2,  1,  0,  2,  1,  0],
        [18,  1, 18, 18,  1, 18],
        [18,  1, 18, 18,  1, 18],
        [ 2,  1,  0,  2,  1,  0],
        [18,  1, 18, 18,  1, 18]]], dtype=int32)

In [114]:
r11=np.ravel(t1)        #returns a flattend 1D array
r11

array([18,  1, 18, 18,  1, 18,  2,  1,  0,  2,  1,  0, 18,  1, 18, 18,  1,
       18, 18,  1, 18, 18,  1, 18,  2,  1,  0,  2,  1,  0, 18,  1, 18, 18,
        1, 18, 18,  1, 18, 18,  1, 18,  2,  1,  0,  2,  1,  0, 18,  1, 18,
       18,  1, 18, 18,  1, 18, 18,  1, 18,  2,  1,  0,  2,  1,  0, 18,  1,
       18, 18,  1, 18, 18,  1, 18, 18,  1, 18,  2,  1,  0,  2,  1,  0, 18,
        1, 18, 18,  1, 18, 18,  1, 18, 18,  1, 18,  2,  1,  0,  2,  1,  0,
       18,  1, 18, 18,  1, 18], dtype=int32)

In [115]:
np.isinf(a5)    #returns bool array for if (+,-)inf is present or not
#arg1 -> input array
#arg2(optional) -> array_name where you want to store
#arg3(optional)-> condition


array([[False, False],
       [False, False],
       [False, False]])

In [116]:
~np.isinf(a5)   #works opposite of isinf()


array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [117]:
a = np.array([np.inf, 2, 0, -np.inf])
out_arr = np.zeros_like(a, dtype=bool)
print(out_arr)
np.isinf(a, out=out_arr, where=(a != 0))        #this can also be used to check for a condition
print(out_arr)  

[False False False False]
[ True False False  True]


In [118]:
np.isrealobj(a6)        #returns true if array has all real objects
#if imaginary/complex part returns false

True

In [119]:
np.isscalar(1)      #returns a bool after checking the element is scalar or not
# scalar is a single digit
#array ,list,matrix etc. are not scalar

True

In [120]:
np.isneginf(a1)     #returns true if element is negative infinity

array([False, False, False, False])

In [121]:
np.isposinf(a1)     #returns true if element is +ve infinity

array([False, False, False, False])

In [122]:
np.iscomplex([1+1j])    #returns true if element is complex,if imaginary part is 0 it will return false

array([ True])

In [123]:
np.isnan(a1)        #returns true if element is NaN
np.isnan(np.nan)

np.True_

In [124]:
np.iscomplexobj(1+0j)    #returns true if element is complex,if imaginary part is 0 it will return true

True

In [125]:
np.isreal(1+0j)     #returns true if element is not complex,if imaginary part is 0 it will return true

True

In [126]:
np.isfinite(a1)     #checks whether element is finite or not
np.isfinite(np.nan)

np.False_

In [127]:
aaa=np.array([[1,2,3],[4,5,6]],order='F')       
np.isfortran(aaa)       #returns true if array is F contigous
# FORTRAN-contiguous order in memory (first index varies the fastest). F order means that column-wise operations will be faster.

True

In [128]:
np.arctan(a1)   # calculates inverse tan of elements

array([0.78539816, 1.10714872, 1.24904577, 1.32581766])

In [129]:
a1

array([1, 2, 3, 4])

In [130]:
a11=np.array([5,4,3,2])

In [131]:
np.hypot(a1,a11)        #returns the hypotenous considering the given elements as P and B
#arg1 -> first input
#arg2 -> second input

array([5.09901951, 4.47213595, 4.24264069, 4.47213595])

In [132]:
np.ceil(ar2)    #returns the ceiling value of a float after roundoff

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [133]:
np.floor(ar2)       #returns the floor value when rounded off

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [134]:
np.degrees(a1)      #returns the value in degress 
# input values are considered to be as radians

array([ 57.29577951, 114.59155903, 171.88733854, 229.18311805])

In [135]:
np.radians(a1)  #returns values in radians
# input values are considered to be as degrees

array([0.01745329, 0.03490659, 0.05235988, 0.06981317])

In [136]:
np.rad2deg(a1)
# same as np.degrees()

array([ 57.29577951, 114.59155903, 171.88733854, 229.18311805])

In [137]:
ra11=np.deg2rad(a1)
#same as np.radians()

In [138]:
np.power(a1,a11)        #a1[i]**a11[i]  
#returns answer in integer array

array([ 1, 16, 27, 16])

In [139]:
np.float_power(a1,a11)  #a1[i]**a11[i]  
#returns answer in float array

array([ 1., 16., 27., 16.])

In [140]:
np.log(a1)      #calculates natural log

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [141]:
np.log10(a1)        #calculates log base 10

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [142]:
np.log1p(a1)    #calculates natural log of (n+1)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [143]:
np.log2(a1)     #calculates log base 2

array([0.       , 1.       , 1.5849625, 2.       ])

In [144]:
np.dot(a2,a11)  #calculates the dot product

array([30, 86])

In [145]:
np.vdot(2+3j,4+5j)

np.complex128(23-2j)

In [146]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])

np.dot(a,b),np.vdot(a,b)    

(array([[12,  9],
        [32, 17]]),
 np.int64(30))

In [147]:

np.vdot(a1,a11),np.dot(a1,a11)

(np.int64(30), np.int64(30))

In [148]:
np.vdot(2+3j,4+5j)      #when complex number is taken as inout ,vdot() takes the complex conjucate of it
# complex conjucate is of (a+bj) is (a-bj)


np.complex128(23-2j)

In [149]:
ar4=np.array([0.324,1.33,22.43322,1.7655])

In [150]:
np.trunc(ar4)       #removes the decimal part of the float value

array([ 0.,  1., 22.,  1.])

In [151]:
np.divide(a1,a11)       #divides arg1/arg2

array([0.2, 0.5, 1. , 2. ])

In [152]:
np.floor_divide(a1,a11)         #floor divides arg1/arg2

array([0, 0, 1, 2])

In [153]:
np.true_divide(a1,a11)      #divides arg1/arg2

array([0.2, 0.5, 1. , 2. ])

In [154]:
a4.flat[0:]        #converts the n dimensinal arry into 1D array ,we have to use slicing  
a4.flat[1:4]       # we also access particular values 

array([2, 3, 4])

In [155]:
np.expm1(a1),a1      #returns the exponential values nius 1
# i.e  [(e=2.71828)**n]-1

(array([ 1.71828183,  6.3890561 , 19.08553692, 53.59815003]),
 array([1, 2, 3, 4]))

In [156]:
np.exp(a1)      #returns exponential values
## i.e  [(e=2.71828)**n]

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [157]:
np.bincount(a1) ,a1    #only works for 1D arrary

# z2=np.zeros((5,),dtype='int')

# np.bincount(z2)

(array([0, 1, 1, 1, 1]), array([1, 2, 3, 4]))

In [158]:
a12=np.array([1,1,1,4,5,7,0])       #counts the occurance of indices in the array 
np.bincount(a12)
#for example 1 has come 3 time,so it is counting 1 as index and printing 3 at index 1 has it has come 3 time and it is true for all

array([1, 3, 0, 0, 1, 1, 0, 1])

In [159]:
np.rint(ra11),ra11      #rounds off the elements to the nearest integer value

(array([0., 0., 0., 0.]),
 array([0.01745329, 0.03490659, 0.05235988, 0.06981317]))

In [160]:
np.cbrt(a12)        #returns the bube root of the elements

array([1.        , 1.        , 1.        , 1.58740105, 1.70997595,
       1.91293118, 0.        ])

In [ ]:
np.ones_like(a2),a2

(array([[1, 1, 1, 1],
        [1, 1, 1, 1]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [162]:
np.full_like(a2,10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [163]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
np.prod(a2,axis=1)      #multiplies elements of the array
#if no axis given multiplies all elements 
# if axis given multiplies along nly the axis

array([  24, 1680])

- Vstack () -> np.vstack is function that stacks the two arrays on the horizontal axis

    Rules -> 
    
    1. all dimensions should be same,apart from the vertical axis
    
        i.e. is number of columns and ndim should be same (x,y,z) x and z should be same for v stack

In [165]:
a1,a11

(array([1, 2, 3, 4]), array([5, 4, 3, 2]))

In [166]:
np.vstack((a1,a11))

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [167]:
a3.shape,a6.shape,a4.shape,a2.shape,a1.shape,a1.ndim,a2.ndim

((1, 3, 4), (3, 3), (2, 2, 4), (2, 4), (4,), 1, 2)

In [168]:
a3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 1, 2]]])

In [169]:
a2,a1

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([1, 2, 3, 4]))

In [170]:
np.vstack((a2,a1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [171]:
# np.vstack((a3,a4))     #these will give error as nmber of columns don't match

In [172]:
# np.vstack((a6,a2))    #these will give error as number of dimensions not match

In [173]:
a4

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 0, 1, 2],
        [3, 4, 5, 6]]])

In [174]:
a7=np.array([[[5,6,7,8],[9,0,1,2]],[[3,4,5,6],[7,8,9,0]]])
a7

array([[[5, 6, 7, 8],
        [9, 0, 1, 2]],

       [[3, 4, 5, 6],
        [7, 8, 9, 0]]])

In [175]:
np.vstack((a7,a4))

array([[[5, 6, 7, 8],
        [9, 0, 1, 2]],

       [[3, 4, 5, 6],
        [7, 8, 9, 0]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 0, 1, 2],
        [3, 4, 5, 6]]])

 - hstack() -> np.hstack() concats the arrays on horizontal axis i.e. coumn wise

    Rules ->
    1. Number of dimensions and rows should be same number of columns can vary

In [176]:
a8=np.random.randint(100,size=(1,3,3))
a8

array([[[46, 59, 73],
        [78, 94, 95],
        [32, 16, 21]]], dtype=int32)

In [177]:
a4,a7

(array([[[1, 2, 3, 4],
         [5, 6, 7, 8]],
 
        [[9, 0, 1, 2],
         [3, 4, 5, 6]]]),
 array([[[5, 6, 7, 8],
         [9, 0, 1, 2]],
 
        [[3, 4, 5, 6],
         [7, 8, 9, 0]]]))

In [178]:
np.hstack((a4,a7))

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8],
        [9, 0, 1, 2]],

       [[9, 0, 1, 2],
        [3, 4, 5, 6],
        [3, 4, 5, 6],
        [7, 8, 9, 0]]])

- dtsack -> np.dstack() stacks the arrays along the third axis i.e. depth

vstack -> doesn't goes inside any brackets 

hstack -> goes inside one bracket

dstack -> goes inside two brackets

In [179]:
np.hstack((a4,a7))

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8],
        [9, 0, 1, 2]],

       [[9, 0, 1, 2],
        [3, 4, 5, 6],
        [3, 4, 5, 6],
        [7, 8, 9, 0]]])

In [180]:
a4, a7

(array([[[1, 2, 3, 4],
         [5, 6, 7, 8]],
 
        [[9, 0, 1, 2],
         [3, 4, 5, 6]]]),
 array([[[5, 6, 7, 8],
         [9, 0, 1, 2]],
 
        [[3, 4, 5, 6],
         [7, 8, 9, 0]]]))

In [181]:
np.dstack((a3,a8))

array([[[ 1,  2,  3,  4, 46, 59, 73],
        [ 5,  6,  7,  8, 78, 94, 95],
        [ 9,  0,  1,  2, 32, 16, 21]]])

In [182]:
a9=np.array([[[1,2],[3,4]]])
a10=np.array([[[5,6],[7,8]]])
a9.shape,a10.shape

((1, 2, 2), (1, 2, 2))

In [183]:
np.dstack((a9,a10))

array([[[1, 2, 5, 6],
        [3, 4, 7, 8]]])

In [184]:
a13=np.array([[1,2],[3,4]])
a14=np.array([[5,6],[7,8]])

np.vstack((a13,a14))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [185]:
a15 = np.array([[[1,3],[2,4]], [[5,6], [7,8]]])
a16 = np.array([[[10,30],[20,40]], [[50,60], [70,80]]])
a15,a16,np.vstack((a15, a16))

(array([[[1, 3],
         [2, 4]],
 
        [[5, 6],
         [7, 8]]]),
 array([[[10, 30],
         [20, 40]],
 
        [[50, 60],
         [70, 80]]]),
 array([[[ 1,  3],
         [ 2,  4]],
 
        [[ 5,  6],
         [ 7,  8]],
 
        [[10, 30],
         [20, 40]],
 
        [[50, 60],
         [70, 80]]]))

In [186]:
a15 = np.array([[[1,3],[2,4]], [[5,6], [7,8]]])
a16 = np.array([[[10,30],[20,40]], [[50,60], [70,80]]])
np.hstack((a15, a16))

array([[[ 1,  3],
        [ 2,  4],
        [10, 30],
        [20, 40]],

       [[ 5,  6],
        [ 7,  8],
        [50, 60],
        [70, 80]]])

In [187]:
a17=np.vstack((a15,a16))

In [188]:
a17

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[10, 30],
        [20, 40]],

       [[50, 60],
        [70, 80]]])

In [189]:
a18=np.random.randint(1,20,size=(4,5))
a19=np.random.randint(1,20,size=(5,3))
a18,a19

(array([[12,  3, 11, 18,  2],
        [ 9, 12, 16, 12,  2],
        [12,  6,  8, 17, 10],
        [16, 18,  6,  3, 17]], dtype=int32),
 array([[11, 17,  5],
        [18, 14,  9],
        [ 6, 10,  5],
        [19,  8,  9],
        [ 8,  5,  9]], dtype=int32))

In [190]:
np.dot(a18,a19),a18@a19

(array([[610, 510, 322],
        [655, 587, 359],
        [691, 554, 397],
        [729, 693, 452]], dtype=int32),
 array([[610, 510, 322],
        [655, 587, 359],
        [691, 554, 397],
        [729, 693, 452]], dtype=int32))

vsplit() -> splits array into sub aarays vertically

In [191]:
np.vsplit(a17,4)        #the split won't happen if splitting the array, meant it is dividing into unequal parts 
#arg1 -> array to be passed
#rg2 -> number of splits 

[array([[[1, 3],
         [2, 4]]]),
 array([[[5, 6],
         [7, 8]]]),
 array([[[10, 30],
         [20, 40]]]),
 array([[[50, 60],
         [70, 80]]])]

In [192]:
np.vsplit(a18,np.array([3,2]))      #it also splits if we provide the indices of the array 

[array([[12,  3, 11, 18,  2],
        [ 9, 12, 16, 12,  2],
        [12,  6,  8, 17, 10]], dtype=int32),
 array([], shape=(0, 5), dtype=int32),
 array([[12,  6,  8, 17, 10],
        [16, 18,  6,  3, 17]], dtype=int32)]

hsplit() -> splits the array horizontally/columns into sub arrays

In [193]:
a15

array([[[1, 3],
        [2, 4]],

       [[5, 6],
        [7, 8]]])

In [194]:
np.hsplit(a15,2)        # arg1 -> array
#arg2 -> number of sub parts

[array([[[1, 3]],
 
        [[5, 6]]]),
 array([[[2, 4]],
 
        [[7, 8]]])]

In [195]:
np.hsplit(a15,np.array([1,1]))      #can't split if resultant has unequal parts 

[array([[[1, 3]],
 
        [[5, 6]]]),
 array([], shape=(2, 0, 2), dtype=int64),
 array([[[2, 4]],
 
        [[7, 8]]])]

In [196]:
np.hsplit(a4,np.array([1,1]))

[array([[[1, 2, 3, 4]],
 
        [[9, 0, 1, 2]]]),
 array([], shape=(2, 0, 4), dtype=int64),
 array([[[5, 6, 7, 8]],
 
        [[3, 4, 5, 6]]])]

In [197]:
np.hsplit(a1,2)

[array([1, 2]), array([3, 4])]

dsplit() ->

In [198]:
a15

array([[[1, 3],
        [2, 4]],

       [[5, 6],
        [7, 8]]])

In [199]:
np.dsplit(a15,2)

[array([[[1],
         [2]],
 
        [[5],
         [7]]]),
 array([[[3],
         [4]],
 
        [[6],
         [8]]])]

In [200]:
a4

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 0, 1, 2],
        [3, 4, 5, 6]]])

In [201]:
a21,b21=np.hsplit(a4,2)     #this way we can store splitted array into different variables

In [202]:
b21

array([[[5, 6, 7, 8]],

       [[3, 4, 5, 6]]])

In [203]:
np.dsplit(a4,2)

[array([[[1, 2],
         [5, 6]],
 
        [[9, 0],
         [3, 4]]]),
 array([[[3, 4],
         [7, 8]],
 
        [[1, 2],
         [5, 6]]])]

column_stack() -> 
1. converts 1D array into 2D array 
2. if already 2D returns transpose 
3. IF 3D matrix and number of matrix is 1 then nothing happens and just converts 3D matrix into 2D matrix
4. In 3D , number of matrix is more than 1,then if performs hstack and converts 3D->2D


- when merging two arrays using column stack
1. if arrays are 1D and 2D column_stack performs dstack 
2. if arrays are 3D column_stack performs hstack

In [204]:
np.column_stack(a2),a2

(array([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [205]:
np.column_stack(a18),a18

(array([[12,  9, 12, 16],
        [ 3, 12,  6, 18],
        [11, 16,  8,  6],
        [18, 12, 17,  3],
        [ 2,  2, 10, 17]], dtype=int32),
 array([[12,  3, 11, 18,  2],
        [ 9, 12, 16, 12,  2],
        [12,  6,  8, 17, 10],
        [16, 18,  6,  3, 17]], dtype=int32))

In [206]:
np.column_stack(a16),a16

(array([[10, 30, 50, 60],
        [20, 40, 70, 80]]),
 array([[[10, 30],
         [20, 40]],
 
        [[50, 60],
         [70, 80]]]))

In [207]:
a22=np.random.randint(30,size=(3,4,2))
a22

array([[[ 6, 19],
        [24,  8],
        [28, 14],
        [21, 17]],

       [[19, 19],
        [27,  3],
        [15,  2],
        [22,  5]],

       [[ 5, 18],
        [ 5, 29],
        [12, 28],
        [ 6, 17]]], dtype=int32)

In [208]:
np.column_stack(a22)

array([[ 6, 19, 19, 19,  5, 18],
       [24,  8, 27,  3,  5, 29],
       [28, 14, 15,  2, 12, 28],
       [21, 17, 22,  5,  6, 17]], dtype=int32)

In [209]:
a23=np.random.randint(30,size=(1,4,2))
a23

array([[[12,  5],
        [16,  5],
        [20, 24],
        [26, 19]]], dtype=int32)

In [210]:
np.column_stack(a23)

array([[12,  5],
       [16,  5],
       [20, 24],
       [26, 19]], dtype=int32)

In [211]:
np.column_stack(a1),a1

(array([[1, 2, 3, 4]]), array([1, 2, 3, 4]))

In [212]:
np.column_stack(a5),a5

(array([[9, 7, 5],
        [8, 6, 4]]),
 array([[9, 8],
        [7, 6],
        [5, 4]]))

In [213]:
a24=np.array((1,2,3))
a25=np.array((4,5,6))

print("hstack",np.hstack((a24,a25)))
print("vstack",np.vstack((a24,a25)))
print("dstack",np.dstack((a24,a25)))

hstack [1 2 3 4 5 6]
vstack [[1 2 3]
 [4 5 6]]
dstack [[[1 4]
  [2 5]
  [3 6]]]


In [214]:
np.column_stack((a24,a25))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [215]:
a26=np.random.randint(10,size=(2,3))
a27=np.random.randint(10,size=(2,3))
a26,a27

(array([[7, 5, 9],
        [4, 5, 2]], dtype=int32),
 array([[6, 0, 5],
        [7, 1, 6]], dtype=int32))

In [216]:
print("hstack",np.hstack((a26,a27)))
print("vstack",np.vstack((a26,a27)))
print("dstack",np.dstack((a26,a27)))

hstack [[7 5 9 6 0 5]
 [4 5 2 7 1 6]]
vstack [[7 5 9]
 [4 5 2]
 [6 0 5]
 [7 1 6]]
dstack [[[7 6]
  [5 0]
  [9 5]]

 [[4 7]
  [5 1]
  [2 6]]]


In [217]:
np.column_stack((a26,a27))

array([[7, 5, 9, 6, 0, 5],
       [4, 5, 2, 7, 1, 6]], dtype=int32)

In [218]:
a28=np.random.randint(10,size=(3,))
a29=np.random.randint(10,size=(3,))
a28,a29

(array([7, 0, 1], dtype=int32), array([2, 4, 0], dtype=int32))

In [219]:
print("hstack",np.hstack((a28,a29)))
print("vstack",np.vstack((a28,a29)))
print("dstack",np.dstack((a28,a29)))

hstack [7 0 1 2 4 0]
vstack [[7 0 1]
 [2 4 0]]
dstack [[[7 2]
  [0 4]
  [1 0]]]


In [220]:
np.column_stack((a28,a29))

array([[7, 2],
       [0, 4],
       [1, 0]], dtype=int32)

In [221]:
a30=np.random.randint(10,size=(2,3,3))
a31=np.random.randint(10,size=(2,3,3))
a30,a31

(array([[[6, 6, 8],
         [6, 9, 5],
         [1, 5, 9]],
 
        [[4, 9, 8],
         [3, 4, 6],
         [2, 4, 7]]], dtype=int32),
 array([[[5, 1, 3],
         [7, 4, 5],
         [1, 2, 3]],
 
        [[6, 1, 2],
         [9, 6, 0],
         [5, 3, 5]]], dtype=int32))

In [222]:
np.column_stack((a30,a31))

array([[[6, 6, 8],
        [6, 9, 5],
        [1, 5, 9],
        [5, 1, 3],
        [7, 4, 5],
        [1, 2, 3]],

       [[4, 9, 8],
        [3, 4, 6],
        [2, 4, 7],
        [6, 1, 2],
        [9, 6, 0],
        [5, 3, 5]]], dtype=int32)

- concatenate() -> merges two arrays into one, based on the axis

In [223]:
a21,b21

(array([[[1, 2, 3, 4]],
 
        [[9, 0, 1, 2]]]),
 array([[[5, 6, 7, 8]],
 
        [[3, 4, 5, 6]]]))

In [224]:
np.concatenate((a21,b21))

array([[[1, 2, 3, 4]],

       [[9, 0, 1, 2]],

       [[5, 6, 7, 8]],

       [[3, 4, 5, 6]]])

In [225]:
np.concatenate((a21,b21[:,:0]),axis=1) #every axis aprt from concatination axis should be same
#like if axis==0, it performs vstack
#if axis ==1,it performs hsatck

array([[[1, 2, 3, 4]],

       [[9, 0, 1, 2]]])

In [226]:
a21,b21

(array([[[1, 2, 3, 4]],
 
        [[9, 0, 1, 2]]]),
 array([[[5, 6, 7, 8]],
 
        [[3, 4, 5, 6]]]))

In [227]:
a32=np.random.randint(10,size=(3,3))        
a33=np.random.randint(10,size=(3,3))
a32,a33

(array([[2, 8, 9],
        [7, 3, 0],
        [4, 6, 2]], dtype=int32),
 array([[7, 9, 3],
        [1, 1, 9],
        [9, 0, 8]], dtype=int32))

In [228]:
np.concatenate((a32,a33),axis=1)

array([[2, 8, 9, 7, 9, 3],
       [7, 3, 0, 1, 1, 9],
       [4, 6, 2, 9, 0, 8]], dtype=int32)

In [229]:
a32,a33.T

(array([[2, 8, 9],
        [7, 3, 0],
        [4, 6, 2]], dtype=int32),
 array([[7, 1, 9],
        [9, 1, 0],
        [3, 9, 8]], dtype=int32))

- array_split() -> splits array into multiple sub arrays

In [230]:
a34=np.random.randint(100,size=(7,7))
a34

array([[10,  8, 99, 46, 35, 78, 79],
       [54, 49,  6, 97, 98, 95, 49],
       [29, 34, 54, 59, 97, 99, 13],
       [12, 47, 83, 58, 44, 66, 31],
       [35, 50, 90, 10, 91, 42, 43],
       [35, 42,  3, 93, 64,  5, 10],
       [11, 94, 81, 82, 65, 86, 34]], dtype=int32)

In [231]:
b2,b3,b4=np.array_split(a34,3)      # if number of sub arrays is more than the size of array then,it it will create remaining arrays as empty arrays
#it divides the array into sub arrays and doesn't worry about the equal size
#axis=0 (by default) -> splits row wise
#axis=1 -> splits column wise
b2,b3,b4

(array([[10,  8, 99, 46, 35, 78, 79],
        [54, 49,  6, 97, 98, 95, 49],
        [29, 34, 54, 59, 97, 99, 13]], dtype=int32),
 array([[12, 47, 83, 58, 44, 66, 31],
        [35, 50, 90, 10, 91, 42, 43]], dtype=int32),
 array([[35, 42,  3, 93, 64,  5, 10],
        [11, 94, 81, 82, 65, 86, 34]], dtype=int32))

In [232]:
b2[:,1]

array([ 8, 49, 34], dtype=int32)

In [246]:
a111=np.random.randint(100,size=(6,4))
a111

array([[28, 80, 73, 46],
       [62, 54, 80, 54],
       [48, 51,  7, 51],
       [63, 64, 88, 53],
       [49, 75, 47, 16],
       [38, 46, 59, 87]], dtype=int32)

In [256]:
a1111=np.where(np.sum(a111,axis=1)>200,1,0)
for i in range(len(a1111)):
    if a1111[i]==1:
        print(a111[i])
a1111

[28 80 73 46]
[62 54 80 54]
[63 64 88 53]
[38 46 59 87]


array([1, 1, 0, 1, 0, 1])