In [1]:
import numpy as np

In [2]:
a1=np.random.randint(10,size=(2,2))
a2=np.random.randint(10,size=(2,3))
a3=np.random.randint(10,size=(3,2))
a1,a2,a3

(array([[6, 3],
        [2, 9]], dtype=int32),
 array([[4, 0, 4],
        [1, 5, 4]], dtype=int32),
 array([[0, 4],
        [2, 0],
        [0, 2]], dtype=int32))

In [3]:
a1@a2,np.dot(a1,a2)     #dot product

(array([[27, 15, 36],
        [17, 45, 44]], dtype=int32),
 array([[27, 15, 36],
        [17, 45, 44]], dtype=int32))

numpy.linalg.multi_dot -> performs dot product on more than two arrays together

In [4]:
np.linalg.multi_dot((a1,a2,a3))

array([[ 30, 180],
       [ 90, 156]], dtype=int32)

np.vdot() -> complex conjucate is takes when first element is complex 
- for higher dimension arrays the resultant is flattend into a single output

In [5]:
np.vdot([2+3j],[5+6j])  #if first term is complex ,the conjucate of only the first tem is taken for dot product

np.complex128(28-3j)

In [6]:
np.vdot(a3,a2)      #flattens the array into a single output

np.int32(16)

In [7]:
a4=np.random.randint(10,size=(2,4))
a5=np.random.randint(10,size=(3,4))
a4,a5

(array([[8, 3, 6, 3],
        [0, 8, 3, 8]], dtype=int32),
 array([[6, 7, 9, 2],
        [1, 8, 9, 4],
        [6, 6, 5, 6]], dtype=int32))

In [8]:
np.vecdot(a4,a5)       #performs the dot product of vectors
#multiplies one to one  

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,4)->(2,) (3,4)->(3,)  and requested shape ()

In [ ]:
np.vdot(a4,a5)   

np.int32(187)

In [ ]:
np.linalg.vecdot(a5,a4)     #same as dot product ,but it is limited to array API only

array([102,  85], dtype=int32)

In [ ]:
a4,a5

(array([[6, 6, 2, 4],
        [4, 0, 4, 0]], dtype=int32),
 array([[9, 8, 3, 4],
        [6, 4, 8, 7],
        [4, 6, 4, 8]], dtype=int32))

In [ ]:
np.inner(a4,a5)     #returns dot product of the two matrices    
# if two matrices of shape [2*4]
#then resultant will be
# [[a1b1],[a1b2]
#   [a2b1],[a2b2]]

# shape of the resultant would be [a[row],b[row]]

array([[124, 104, 100],
       [ 48,  56,  32]], dtype=int32)

In [ ]:
a4,a5

(array([[2, 6, 6, 0],
        [7, 4, 6, 7]], dtype=int32),
 array([[3, 7, 9, 2],
        [0, 5, 5, 5]], dtype=int32))

In [ ]:
a4.shape,a5.shape

((2, 4), (2, 4))

In [ ]:
np.outer(a4,a5) #returns an array of values of each number of a1 * each number of a2
# converts the ndim array into 1D if greater dim array is given

array([[ 6, 14, 18,  4,  0, 10, 10, 10],
       [18, 42, 54, 12,  0, 30, 30, 30],
       [18, 42, 54, 12,  0, 30, 30, 30],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [21, 49, 63, 14,  0, 35, 35, 35],
       [12, 28, 36,  8,  0, 20, 20, 20],
       [18, 42, 54, 12,  0, 30, 30, 30],
       [21, 49, 63, 14,  0, 35, 35, 35]], dtype=int32)

In [ ]:
a6=np.random.randint(10,size=(4,))
a7=np.random.randint(10,size=(5,))
a6,a7

(array([7, 2, 1, 5], dtype=int32), array([1, 5, 8, 6, 6], dtype=int32))

In [ ]:
a6.shape,a7.shape

((4,), (5,))

In [ ]:
np.linalg.outer(a6,a7)  #for linalg.outer ndim should only be 1 and it works same as outer

array([[ 7, 35, 56, 42, 42],
       [ 2, 10, 16, 12, 12],
       [ 1,  5,  8,  6,  6],
       [ 5, 25, 40, 30, 30]], dtype=int32)

In [ ]:
a8=np.random.randint(10,size=(3,2))
a9=np.random.randint(10,size=(3,3,3))

In [ ]:
np.outer(a8,a9)

array([[  3,  52,  54,  47,  21,  94, 108,  59,  18,  62,  74,  32,  12,
         58,  66,  38],
       [ 27, 468, 486, 423, 189, 846, 972, 531, 162, 558, 666, 288, 108,
        522, 594, 342],
       [ 21, 364, 378, 329, 147, 658, 756, 413, 126, 434, 518, 224,  84,
        406, 462, 266],
       [ 27, 468, 486, 423, 189, 846, 972, 531, 162, 558, 666, 288, 108,
        522, 594, 342],
       [ 18, 312, 324, 282, 126, 564, 648, 354, 108, 372, 444, 192,  72,
        348, 396, 228],
       [ 12, 208, 216, 188,  84, 376, 432, 236,  72, 248, 296, 128,  48,
        232, 264, 152],
       [ 12, 208, 216, 188,  84, 376, 432, 236,  72, 248, 296, 128,  48,
        232, 264, 152],
       [ 18, 312, 324, 282, 126, 564, 648, 354, 108, 372, 444, 192,  72,
        348, 396, 228]], dtype=int32)

In [ ]:
# np.linalg.outer(a4,a5)        #it won't work for ndim greater than 1

In [ ]:
a8=np.random.randint(10,size=(4,2))

In [ ]:
np.matmul(a5,a6)        #works similar to dot product   

array([54, 40], dtype=int32)

In [ ]:
np.matmul(a5,a8)       

array([[114, 138],
       [ 85,  95]], dtype=int32)

In [ ]:
np.matmul(a8,a5)

array([[  3,  52,  54,  47],
       [ 21,  94, 108,  59],
       [ 18,  62,  74,  32],
       [ 12,  58,  66,  38]], dtype=int32)

In [ ]:
a9=np.linalg.matmul(a8,a5)
a9

array([[  3,  52,  54,  47],
       [ 21,  94, 108,  59],
       [ 18,  62,  74,  32],
       [ 12,  58,  66,  38]], dtype=int32)

In [ ]:
np.linalg.matmul(a5,a6)     #works similar to matmul

array([54, 40], dtype=int32)

In [ ]:
a5,a4

(array([[3, 7, 9, 2],
        [0, 5, 5, 5]], dtype=int32),
 array([[2, 6, 6, 0],
        [7, 4, 6, 7]], dtype=int32))

In [ ]:
a8.shape,a5.shape

((4, 2), (2, 4))

In [ ]:
a10=np.random.randint(10,size=(4,4))

In [ ]:
np.matvec(a5,a10)

array([[100,  90],
       [ 36,  10],
       [ 71,  60],
       [ 77,  45]], dtype=int32)

In [ ]:
np.matmul(a5,a10)        #number of columns should be same

array([[85, 62, 56, 76],
       [80, 55, 25, 35]], dtype=int32)

In [ ]:
np.transpose(a4)

array([[2, 7],
       [6, 4],
       [6, 6],
       [0, 7]], dtype=int32)

In [ ]:
np.linalg.det(a10)      #determinant of the matrix

np.float64(378.0000000000001)

In [ ]:
np.linalg.inv(a10)      #returns the invers of the matrix

array([[ 0.14285714,  0.07936508, -0.29100529,  0.08465608],
       [-0.28571429, -0.04761905,  0.50793651,  0.01587302],
       [-0.42857143,  0.26190476,  0.87301587, -0.25396825],
       [ 0.42857143, -0.15079365, -0.61375661,  0.10582011]])

In [ ]:
np.linalg.pinv(a10,hermitian=True) #calculates the (Moore-Penrose) pseudo inverse of the matrix

array([[-0.10061832,  0.0831928 , -0.04384486,  0.11129848],
       [ 0.0831928 , -0.10230467,  0.08094435,  0.02529511],
       [-0.04384486,  0.08094435,  0.25463744, -0.1079258 ],
       [ 0.11129848,  0.02529511, -0.1079258 , -0.03372681]])

x0 + 2 * x1 = 1 and 3 * x0 + 5 * x1 = 2:

In [ ]:
a2.shape,a1.shape

((2, 3), (2, 2))

In [ ]:
a1,a2

(array([[3, 9],
        [0, 0]], dtype=int32),
 array([[1, 1, 9],
        [2, 2, 7]], dtype=int32))

In [ ]:
a11=np.random.randint(100,size=(2,2))
a12=np.random.randint(10,size=(2,))
a11,a12

(array([[72,  4],
        [ 4, 70]], dtype=int32),
 array([4, 1], dtype=int32))

In [ ]:
np.linalg.solve(a11,a12)      #solve the system of linear equation

array([0.05493631, 0.0111465 ])

In [ ]:
np.linalg.lstsq(a11,a12)      #returns the least squared solution of the system of linear algebra

#output 1 -> array of least squared solutions
#output 2 -> Sums of squared residuals: 
#output 3 -> Rank of matrix
#output 4 -> singular value of matrix a

(array([0.05493631, 0.0111465 ]),
 array([], dtype=float64),
 np.int32(2),
 array([75.12310563, 66.87689437]))

In [ ]:
x = np.array([[0, 1, 2, 3]])
y = np.array([[-1, 0.2, 0.9, 2.1]])
np.linalg.lstsq(x,y)

(array([[ 0.        ,  0.        ,  0.        ,  0.        ],
        [-0.07142857,  0.01428571,  0.06428571,  0.15      ],
        [-0.14285714,  0.02857143,  0.12857143,  0.3       ],
        [-0.21428571,  0.04285714,  0.19285714,  0.45      ]]),
 array([], dtype=float64),
 np.int32(1),
 array([3.74165739]))

In [ ]:
r1=([[1,2,1],[-2,-3,1],[3,5,0]])

In [ ]:
np.linalg.matrix_rank(r1)       #returns the rank of the matrix
#rank is the number of rows or columns that are linearly independenx1t

np.int64(2)

# Questions

In [13]:
a13=np.random.randint(1,49,size=(7,7))
a13

array([[ 7, 13, 37, 44,  6, 47,  5],
       [ 6, 18, 35, 44, 11, 11,  9],
       [44, 33, 17, 19,  1, 40,  8],
       [ 7, 39, 48,  6, 47, 11,  8],
       [29,  7, 16, 32, 16, 40,  5],
       [31, 20, 11, 42, 25, 43, 20],
       [33, 10, 35, 26, 17, 23, 48]], dtype=int32)

In [14]:
np.diag(a13)

array([ 7, 18, 17,  6, 16, 43, 48], dtype=int32)

In [19]:
for i in range(len(a13)):
    a13[i,i]=-999

In [20]:
a13

array([[-999,   13,   37,   44,    6,   47,    5],
       [   6, -999,   35,   44,   11,   11,    9],
       [  44,   33, -999,   19,    1,   40,    8],
       [   7,   39,   48, -999,   47,   11,    8],
       [  29,    7,   16,   32, -999,   40,    5],
       [  31,   20,   11,   42,   25, -999,   20],
       [  33,   10,   35,   26,   17,   23, -999]], dtype=int32)

In [23]:
np.where(a13==np.diag(a13),-999,a13)

array([[-999,   13,   37,   44,    6,   47,    5],
       [   6, -999,   35,   44,   11,   11,    9],
       [  44,   33, -999,   19,    1,   40,    8],
       [   7,   39,   48, -999,   47,   11,    8],
       [  29,    7,   16,   32, -999,   40,    5],
       [  31,   20,   11,   42,   25, -999,   20],
       [  33,   10,   35,   26,   17,   23, -999]], dtype=int32)

Conditional Replacement with np.where Generate a 1D array of 50 random integers between 10 and 90. Replace all values > 60 with 1 and ≤ 60 with 0 using np.where.

In [42]:
a14=np.random.randint(10,91,size=(50,))
a14

array([46, 83, 83, 36, 84, 69, 64, 51, 39, 76, 29, 50, 66, 47, 28, 77, 36,
       56, 71, 21, 32, 57, 21, 36, 88, 27, 69, 44, 80, 84, 86, 15, 58, 44,
       16, 64, 81, 17, 84, 22, 28, 57, 76, 70, 75, 69, 58, 23, 75, 49],
      dtype=int32)

In [52]:
a14a=np.where(a14<=60,0,a14)
a14a

array([ 0, 83, 83,  0, 84, 69, 64,  0,  0, 76,  0,  0, 66,  0,  0, 77,  0,
        0, 71,  0,  0,  0,  0,  0, 88,  0, 69,  0, 80, 84, 86,  0,  0,  0,
        0, 64, 81,  0, 84,  0,  0,  0, 76, 70, 75, 69,  0,  0, 75,  0],
      dtype=int32)

In [53]:
np.where(a14a>60,1,a14a)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0], dtype=int32)

In [ ]:
np.where(a14>60,1,0)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0])

In [56]:
np.where(a14<60,0,np.where(a14>70,2,a14))

array([ 0,  2,  2,  0,  2, 69, 64,  0,  0,  2,  0,  0, 66,  0,  0,  2,  0,
        0,  2,  0,  0,  0,  0,  0,  2,  0, 69,  0,  2,  2,  2,  0,  0,  0,
        0, 64,  2,  0,  2,  0,  0,  0,  2, 70,  2, 69,  0,  0,  2,  0],
      dtype=int32)

In [59]:
a15=np.random.randint(21,size=[21,])
a15

array([ 7, 16, 12,  1, 16,  0,  5,  0,  8,  7,  8, 11, 18, 16,  0,  4,  5,
       13,  8, 17,  3], dtype=int32)

In [ ]:
np.cumsum(a15)  #returns the cummulative sum like accumulate

array([  7,  23,  35,  36,  52,  52,  57,  57,  65,  72,  80,  91, 109,
       125, 125, 129, 134, 147, 155, 172, 175])

In [ ]:
np.cumprod(a15) #returns the cummulative product like accumulate

array([    7,   112,  1344,  1344, 21504,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0])

Array Tiling and Repetition Create a 1D array [1, 2, 3]. Repeat each element 3 times using np.repeat() and then tile the entire array 2 times using np.tile().

In [66]:
a16=np.array([1,2,3])
a16r=np.repeat(a16,3)   #repeates each element n times
np.tile(a16r,2)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1, 2, 2, 2, 3, 3, 3])

Set Operations Given two 1D arrays a = [1, 2, 3, 4] and b = [3, 4, 5, 6], find their union, intersection, and set difference (a - b).

In [68]:
a17=np.array([1,2,3,4])
a18=np.array([3,4,5,6])
a17,a18

(array([1, 2, 3, 4]), array([3, 4, 5, 6]))

In [74]:
sa17,sa18=set(a17),set(a18)

In [80]:
u1718=sa17.union(sa18)
u1718

{np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)}

In [81]:
sa17.intersection(sa18)

{np.int64(3), np.int64(4)}

In [84]:
sa18 - sa17

{np.int64(5), np.int64(6)}