In [3]:
import numpy as np

1. Create a NumPy array of integers from 10 to 50 (inclusive) and print all even numbers from it.

In [4]:
even_number=np.arange(10,51)
even_number1=even_number[even_number %2 ==0]
even_number1,even_number

(array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
        44, 46, 48, 50]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49, 50]))

2. Generate a 3×3 identity matrix using NumPy.

In [5]:
idenitty_arr=np.identity(3)
idenitty_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3. Find the mean, median, and standard deviation of a NumPy array [2, 4, 6, 8, 10].

In [6]:
arr=np.array((2,4,6,8,10))
arr_mean=np.mean(arr)
arr_median=np.median(arr)
arr_sd=np.std(arr)

print(arr_mean,arr_median,arr_sd)

6.0 6.0 2.8284271247461903


4. Reshape a 1D array of 16 elements into a 4×4 matrix and print its transpose.



In [7]:
rnd_arr=np.random.randint(20,size=(1,16))
print(rnd_arr.shape)
reshape_arr=rnd_arr.reshape(4,4)
print(reshape_arr.shape)

(1, 16)
(4, 4)


5. Create two arrays, A = [1, 2, 3] and B = [4, 5, 6]. Perform element-wise addition, subtraction, multiplication, and division using NumPy functions.

In [8]:
a=np.array((1,2,3))
b=np.array((4,5,6))

addi=a+b
sub=a-b
mul=a*b
div=a/b

print(addi,sub,mul,div)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


6. Create a 5×5 random matrix and replace all values greater than 0.5 with 1, and others with 0.

In [9]:
arr=np.random.random((5,5))
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if arr[i][j]>=0.5:
            arr[i][j]=1
        else:
            arr[i][j]=0
arr

array([[1., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1.],
       [1., 0., 0., 1., 0.]])

7. Stack two arrays vertically and horizontally. Example:

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [10]:
A=np.array(((1,2),(3,4)))
B=np.array(((5,6),(7,8)))
A,B

AB_hStack=np.hstack((A,B))
AB_vStack=np.vstack((A,B))

print(AB_hStack)
print()
print(AB_vStack)

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


8. Extract the diagonal elements of a given 4×4 matrix and find their sum.



In [11]:
arr=np.random.randint(100,size=(4,4))
dia_arr=np.diag(arr)
sum=np.sum(dia_arr)
            
print("Array is  -> \n",arr)
print("\nSum of Diagonal is ->",sum)        

Array is  -> 
 [[ 2 67 12  5]
 [65 66 26 67]
 [63 22 36 60]
 [17 52 60 96]]

Sum of Diagonal is -> 200


9. Generate a random array of size 10 and normalize it so that the total sum of all elements becomes 1.



In [12]:
arr=np.random.randint(100,size=(10))
nrm_arr=arr/np.sum(arr)
print("Array is -> \n",arr)
print("\nNormalised Array is -> \n",nrm_arr)

Array is -> 
 [48 38 68 46 92 43 91  3 68 40]

Normalised Array is -> 
 [0.08938547 0.0707635  0.12662942 0.08566108 0.17132216 0.08007449
 0.16945996 0.00558659 0.12662942 0.0744879 ]


10. Write a function using NumPy that takes two matrices as input and returns their dot product if possible, otherwise prints “Matrix multiplication not possible”.

In [13]:
def dot_prod(arr1,arr2):
    try:
        dot_arr=np.dot(arr1,arr2)
        return dot_arr
    except ValueError:
        return "Matrix Multiplication not possible"
    
x=dot_prod(A,B)
x
   

array([[19, 22],
       [43, 50]])

11. Broadcasting & Conditional Replacement

Create a 10×10 random array of integers between 1–100. Replace all even numbers with their half value and all odd numbers with their double value using NumPy vectorized operations (without loops).

In [14]:
np.random.seed(1)
arr=np.random.randint(1,100,size=(10,10))
n_arr=np.where(arr %2==0,arr/2,arr*2)
n_arr

array([[ 19.,  26., 146.,   5.,  38.,   3.,  40., 130.,  34.,   1.],
       [154.,  36.,  14.,  13., 102.,  42.,  38., 170.,   6.,  58.],
       [ 15.,  30., 102., 138.,  44.,  44., 190., 194., 174.,   7.],
       [  5.,   4.,  32.,  31.,  46.,  29.,   1.,   2., 122.,  41.],
       [ 18., 178.,   7.,  24., 146.,  62.,  36.,   2., 142.,  11.],
       [ 25.,  29.,   2., 138.,  50.,  22., 154.,  54., 106., 162.],
       [ 21., 166.,   8., 130., 138.,  13., 198.,  44.,   4.,  54.],
       [ 13.,  46.,   5.,  34.,  12.,  14.,  19.,  29.,  42.,  78.],
       [ 18.,  66.,  70.,  22.,  12.,   8.,  44.,  13.,  36., 186.],
       [150., 126.,  94.,  66., 178.,  12.,  28.,  33.,  39.,   2.]])

12. Advanced Indexing & Masking

Given a 5×5 matrix of random floats between 0–1, find and replace all elements greater than the mean of the matrix with 1 and all elements less than or equal to the mean with 0.

In [15]:
arr=np.random.random((5,5)  )
an_arr=np.where(arr>np.mean(arr),1,0)
an_arr

array([[1, 1, 0, 0, 1],
       [0, 1, 1, 0, 1],
       [0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 0]])

13. Linear Algebra Challenge

Create a 3×3 matrix with random integers between 1–10. Compute:

Determinant

Inverse (if possible)

Eigenvalues and eigenvectors

In [16]:
def det(arr):
    return np.linalg.det(arr)

def inverse(arr):
    try:
        return np.linalg.inv(arr)
    except np.linalg.LinAlgError:
        return "Array OInverse doesn't exist"

def eigen_values_and_vector(arr):
    return np.linalg.eig(arr)


arr=np.random.randint(30,size=(3,3))

x= det(arr)
y=inverse(arr)
z,vect=eigen_values_and_vector(arr)
print("Aray is ->\n",arr)
print("\nDeterminat array is ->",x,"\n\nInverse of the array is -> \n",y,"\n\nEigen Values ->",z,"\n\nEigen Vectors ->\n",vect)


Aray is ->
 [[19  1  2]
 [12 28  7]
 [ 2 10 22]]

Determinat array is -> 10251.999999999989 

Inverse of the array is -> 
 [[ 0.0532579  -0.00019508 -0.00477956]
 [-0.02438549  0.04038236 -0.01063207]
 [ 0.00624268 -0.01833789  0.05072181]] 

Eigen Values -> [35.3035533 +0.j         16.84822335+2.55598668j 16.84822335-2.55598668j] 

Eigen Vectors ->
 [[ 0.12270001+0.j          0.17395358+0.3327639j   0.17395358-0.3327639j ]
 [ 0.78436802+0.j          0.378115  -0.27141056j  0.378115  +0.27141056j]
 [ 0.60803907+0.j         -0.80148218+0.j         -0.80148218-0.j        ]]


14. Multi-dimensional Array Manipulation

Create a 3×3×3 array of integers between 1–50.

Compute the sum along each axis (axis 0, axis 1, axis 2).

Find the maximum element in the entire 3D array and its index.

In [19]:
arr1=np.random.randint(1,50,size=(3,3,3))
sum_axis0=0
sum_axis1=0
sum_axis2=0
res_arr_axis0=np.ones((3,3))

print(res_arr_axis0)

def axis0_sum(arr):
    i,j,k=arr.shape
    return res_arr_axis0
x=axis0_sum(arr1)
x


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
arr1=np.random.randint(1,50,size=(3,3,3))
arr1

array([[[26, 15, 14],
        [21, 44,  7],
        [14, 16, 25]],

       [[10,  3,  8],
        [ 6, 37, 38],
        [22, 41, 14]],

       [[28, 48, 14],
        [41, 15, 46],
        [24, 17, 29]]], dtype=int32)

15. NumPy + Python Functions + Logic

Write a function that takes a NumPy array of student marks (shape: 5 students × 5 subjects) and:

Normalizes the marks of each student to a scale of 0–1.

Computes the average normalized marks for each student.

Returns a list of tuples: (student_index, average_normalized_mark, grade) where grade is:

A → ≥0.8

B → ≥0.6

C → ≥0.4

F → <0.4